quotes = [
    "You also have permission to tickle Tom now",
    "Well fudge",
    "Damn it, that's what I get for working in situ on VIM.  VPN dropped",
    "Yeah, turns out, I'm just a horse's a**",
    "Who...am I?",
    "Ha, Oh, I'm always watching",
    "I bet if we summoned Linus Torvalds, first, we'd notice what a f*cking weird dude he is",
    "I will slap someone if you don't get a UAT response by end of day",
    "Haha, damn it. GET OUT OF MY HEAD!!!",
    "I have a spreadsheet titled 'PB Bureaucracy Navigation'",
    "Well, Gabby just got up, walked across the living room (the big event)....and slapped the dog",
    "Just saw a dude with a giant juggalo tattoo biking next to his friend with a duster and matrix glasses going by...my day might need to end",
    "If I type 'cocker'....one more time",
    "As a capitalist merc with proletariat tendencies, I endorse this private room",
    "Don't start projects you don't plan on finishing (Or Something Like That)",
    "If we hire another midwesterner, I'll show up, scream 'There can be only ONE!' and disembowel said individual.",
    "David Letterman, he went to my high school.",
    "Don't Google that if you're unsure.",
    "I've always enjoyed this article (no relation).",
    "You're such a Cathy.",
    "I come for the beer...I stay for the 'WHAT THE F*CK ARE YOU TALKING ABOUT?'",
    "I'm no Quant, so who knows. But I am a die Bayesian enthusiast.",
    "Watch out for Lithuanians.",
    "File that under Abso then lutely",
    "Give this man a raise NOTE: Aaron Burgess has no control over raises.",
    "Until my coke empire takes over",
    "Sorry man, distractions everywhere",
    "That's what I figured, but I go around repeating what people tell me",
    "Tacos",
    "Run around my yard naked.  Is it really worth their time to chase me?",
    "I’ll false alarm you!",
    "Preparing to tell you",
    "No!  I don't know what that means!",
    "Bouncing around a bit, trying to keep up here",
    "Ha, mine is more sultry",
    "I think I'm at an age where a fanny pack is sounding fine",
    "Did you say, "He will make HR blush"?",
    "I listen to Eazy E",
    "DAMN SKIPPY!",
    "We could reshoot Groundhog Day with me and Prime",
    'Those moments when you find out things retrospectively that make you go, "What?"',
    "Oh...ha...(GET THERE FASTER AARON)"',
    "It's an existential crisis gift wrapped in a ridiculous package",
    "HOW DARE YOU ADDRESS ME WITHOUT ANSWERS!!!",
    "Oh, you're being ignored",
    "You get a pretzel",
    "And role of trojan horse is played by Danbury",
]
