quotes = [
    "You also have permission to tickle Tom now",
    "Well fudge",
    "Damn it, that's what I get for working in situ on VIM.  VPN dropped",
    "Yeah, turns out, I'm just a horse's a**",
    "Who...am I?",
    "Ha, Oh, I'm always watching",
    "I bet if we summoned Linus Torvalds, first, we'd notice what a f*cking weird dude he is",
    "I will slap someone if you don't get a UAT response by end of day",
    "Haha, damn it. GET OUT OF MY HEAD!!!",
    "I have a spreadsheet titled 'PB Bureaucracy Navigation'",
    "Well, Gabby just got up, walked across the living room (the big event)....and slapped the dog",
    "Just saw a dude with a giant juggalo tattoo biking next to his friend with a duster and matrix glasses going by...my day might need to end",
    "If I type 'cocker'....one more time",
    "As a capitalist merc with proletariat tendencies, I endorse this private room",
    "Don't start projects you don't plan on finishing (Or Something Like That)",
    "If we hire another midwesterner, I'll show up, scream 'There can be only ONE!' and disembowel said individual.",
    "David Letterman, he went to my high school.",
    "Don't Google that if you're unsure.",
    "I've always enjoyed this article (no relation).",
    "You're such a Cathy.",
    "I come for the beer...I stay for the 'WHAT THE F*CK ARE YOU TALKING ABOUT?'",
    "I'm no Quant, so who knows. But I am a die Bayesian enthusiast.",
    "Watch out for Lithuanians.",
    "File that under Abso then lutely",
    "Give this man a raise NOTE: Aaron Burgess has no control over raises.",
]
